version: '3.8'
services:
  redis:
    image: redis:6.0
    ports:
      - 6379:6379
  mongo:
    image: mongo:rc-xenial
    restart: always
    ports:
      - 27017:27017
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mongo
  listener:
    restart: always
    image: listener
    build: .
    env_file:
      - .env
    depends_on:
      - mongo
      - redis
  api:
    restart: always
    image: api
    build:
      context: .
      dockerfile: api/Dockerfile
    env_file:
      - .env
    depends_on:
      - listener
    ports:
      - 1323:1323